name: Math Util Repo applying CI

on:
  push:
    branches: ["main"] # Bất kỳ khi nào ai đó push code lên main
  pull_request:
    branches: ["main"]
                    # thì làm các việc dưới đây
jobs:
  build:

    runs-on: ubuntu-latest #1 Mượn 1 cái server của Mỹ, cài sẵn hệ điều hành Ubuntu

    steps:                             #2. Làm các bước sau trên server mượn
    - uses: actions/checkout@v3        #2.1 Lấy toàn bộ code từ kho chuyển qua server
    - name: Set up JDK 20              #2.2 Mượn JDK trên server
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven          #2.3 Chuẩn bị chạy lệnh đóng gói app
      run: mvn -B package --file pom.xml
